load("@npm//:defs.bzl", "npm_link_all_packages")
load("@aspect_bazel_lib//lib:directory_path.bzl", "directory_path")
load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_run_binary")

npm_link_all_packages(name = "node_modules")

directory_path(
    name = "taro_entry",
    directory = ":node_modules/@tarojs/cli/dir",
    path = "bin/taro",
)

js_binary(
    name = "taro_cli",
    data = [
        ":node_modules",
        "//:node_modules",
    ],
    entry_point = ":taro_entry",
)

js_run_binary(
    name = "build",
    tool = ":taro_cli",
    args = [
        "build",
        "--type",
        "weapp",
    ],
    chdir = package_name(),
    srcs = glob([
        "config/**/*",
        "src/**/*",
        "babel.config.js",
        "project.config.json",
        "tsconfig.json",
    ]) + [
        ":node_modules",
        "//:node_modules",
        "package.json",
        "//packages/shared:shared",
    ],
    out_dirs = ["dist"],
    visibility = ["//visibility:public"],
)

js_binary(
    name = "dev",
    args = [
        "build",
        "--type",
        "weapp",
        "--watch",
    ],
    chdir = package_name(),
    data = glob([
        "config/**/*",
        "src/**/*",
        "babel.config.js",
        "project.config.json",
        "tsconfig.json",
    ]) + [
        ":node_modules",
        "//:node_modules",
        "package.json",
        ":node_modules/@tarojs/cli",
        "//packages/shared:shared",
    ],
    entry_point = ":taro_entry",
    visibility = ["//visibility:public"],
)
