packages:
  - "packages/*"
  - "frontend/*"

overrides:
  resolve: 1.22.10

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tarojs/binding"
  - core-js
  - core-js-pure
  - esbuild

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  "@tarojs/binding": true
  core-js: true
  core-js-pure: true
  esbuild: true
